name: Docker Installer Download

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
         curl -o SteamSetup.exe "https://media.st.dl.eccdnx.com/client/installer/SteamSetup.exe"
         curl -o steam.dmg "https://media.st.dl.eccdnx.com/client/installer/steam.dmg"
         curl -o steam.deb "https://media.st.dl.eccdnx.com/client/installer/steam.deb"
         

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          SteamSetup.exe
          steam.dmg 
          steam.deb
          
        tag_name: steam-download
